### ISSUE TITLE
Real-world usage

### ISSUE THREAD

**Issue by MrZoidberg** [jpkeisala/uCookieConsent#2]
I'm wondering if there is any real-world usage of this library, so I can better understand what text do I need to put into each section? Thanks!

**Comment by jpkeisala** [comment]
I use it in here https://www.madskoler.dk/. It was inspired by Wordpress plugin https://www.mooveagency.com/wordpress-plugins/gdpr-cookie-compliance/  take a look plugin site for screenshots.
I have new version coming up (only for Umbraco 9.x) with documentation and screenshots. It wont be in this month but later.

**Comment by MrZoidberg** [comment]
Thanks a lot for the information!

**Comment by orkunsenturk** [comment]
Hi jpkeisala
Any news about the package for the current versions of Umbraco?
Best.

**Comment by jpkeisala** [comment]
@orkunsenturk Yes, I am not working on this plugin anymore. 

I am currently building Analytics Reporting -plugin (Integrations with Google Analytics and Matomo). It is going to be released in September. Once I have the Analytics Reporting -plugin ready I will incorporate Cookie Disclaimer as part of it. If you are intrested testing it, let me know.
